"""add_username_and_title_fields

Revision ID: 7438dc26c773
Revises: 002
Create Date: 2025-10-27 09:44:06.821775

"""
from alembic import op
import sqlalchemy as sa


revision = '7438dc26c773'
down_revision = '002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('title', sa.String(length=200), nullable=False))
    op.add_column('users', sa.Column('username', sa.String(), nullable=False))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'username')
    op.drop_column('reports', 'title')
    # ### end Alembic commands ###
